[package]
name = "fundaziun-davaz"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[[bin]]
name = "stiftungen"
path = "src/stiftungen.rs"

[[bin]]
name = "bildinventar"
path = "src/bildinventar.rs"

[[bin]]
name = "stellungnahme"
path = "src/stellungnahme.rs"

[dependencies]
anyhow = "1"
genpdf = { version = "0.2", features = ["images"] }
lopdf = "0.34"
